from biblioteca import *
vaquinha1 = Vaca('mimosa', 'preta')
vaquinha1.emitirSom()
vaquinha1.comer('mato')
dog1 = Cachorro('yolanda', 'preta')
dog1.comer('ração')
dog1.emitirSom()
coelhinho1 = Coelho('perna longa', 'branco')
coelhinho1.comer('cenoura')
coelhinho1.emitirSom()
coelhinho1.dormir()
calopsita1 = Calopsita('elvis', 'amarelo')
calopsita1.comer('alpiste')
calopsita1.emitirSom()